platform :ios, '8.0'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'SDAutoLayout'
pod 'SDCycleScrollView'
pod 'Masonry'
pod 'JSONKit', '~> 1.5pre'
pod 'Reachability'
pod 'MJExtension'
pod 'MBProgressHUD'